update pipeline

diff --git a/.github/workflows/pre-prod-cicd.yml b/.github/workflows/pre-prod-cicd.yml
--- a/.github/workflows/pre-prod-cicd.yml
+++ b/.github/workflows/pre-prod-cicd.yml
@@ -1,35 +1,50 @@
 name: pre-prod-ci-cd
+run-name: Running pipeline on branch ${{github.ref}} on event ${{github.action}} by ${{github.actor}}
 on:
   workflow_dispatch:
     inputs:
-      environment:
+      deploy-on:
         description: "Select environment"
         required: true
         type: choice
         options:
+          - test
           - dev
-          - staging
-          - prod
+
   push:
     branches:
-    - develop
+      - develop
   pull_request:
     branches:
-    - develop
+      - develop
+env:
+  - BRANCH_NAME: "develop"
+  - DOTNET_VERSION: "9.0.x"
 jobs:
   build-test-deploy:
     runs-on: ubuntu-latest
+
     steps:
-      - name: Environment detail
-        run: echo "Environment - ${{github.event.inputs.environment}}, Triggered by event - ${{github.event_name}}, Branch - ${{github.ref}}"
+      - name: Verify running against ${{env.BRANCH_NAME}} branch
+        run: |
+          if [ "${{ github.ref }}" != "refs/heads/${{env.BRANCH_NAME}}" ]; then
+            echo "Error: This workflow can only be run on the ${{env.BRANCH_NAME}} branch."
+            exit 1
+          fi
+          echo "Running on the correct branch: ${{env.BRANCH_NAME}}"
+
+      - name: Execution Environment Details
+        run: echo "Environment - ${{github.event.inputs.environment}}, Triggered by event - ${{github.event_name}}"
 
       - name: Checkout Repository
         uses: actions/checkout@v4
+        with:
+          ref: ${{env.BRANCH_NAME}}
 
-      - name: Setup .NET SDK 9.0.x
+      - name: Setup .NET SDK ${{env.DOTNET_VERSION}}
         uses: actions/setup-dotnet@v4
         with:
-          dotnet-version: 9.0.x
+          dotnet-version: ${{env.DOTNET_VERSION}}
 
       - name: Build
         run: dotnet build --configuration Release
